#
# This example demonstrates how to configure your TableDog instance.
#

files:
  prerouting: /etc/uninat/prerouting.table
  postrouting: /etc/uninat/postrouting.table

server:
  bind:
    address: localhost
    port: 24902

  backlog: 24

dirty-timeout: 50000
